### ISSUE TITLE
Upload to Thunderstore?

### ISSUE THREAD

**Issue by xXPancakeXx** [JohnDowson/CropReplant#1]
Can you add your mod to the following mod portal? https://valheim.thunderstore.io/
Would really appreciate it, because I am using a modmanager which accesses mods from there.
If you simply just don't have time for that or don't care I could upload it on the site as well.

**Comment by Ivan0xFF** [comment]
I went ahead and uploaded the mod to Thunderstore under my account here, giving the original author full credit: https://valheim.thunderstore.io/package/Ivan0xFF/CropReplant/

Let me know if you want to upload it yourself and I'll take it down.

**Comment by Rusty-Shackleford** [comment]
Just my 2 cents... it generally isn't a great idea from a distribution perspective.  For each portal you want to add the the mod to, you'd have to keep them all up to date with the latest files, release notes, etc.  The more copies on the more sites out there, the more confusion in general.  At least gamers have been using Nexus forever now.  GitHub is the source control of the mod, a well-trusted site that provides value for developers and users alike, and a distribution channel in its own right, so even Nexus feels redundant to me...

Thanks for this mod @JohnDowson !  Excellent work.

**Comment by BSteezie** [comment]
Rusty, the reason people are asking for Thunderstore uploading is Nexus mod managers like Vortex don’t work with Unity games like Valheim.  R2Modman and Thunderstore Mod Manager do, and do it really well, but it pulls mods and updates from Thunderstore only.  Thunderstore seems I’ve used Nexus and Vortex for Skyrim, Fallout 4, and Cyberpunk 2077, and frankly it sucks.  I use R2Modman, but the TMM looks identical and should work the same.  R2Modman has a much nicer to use interface than Vortex, lets you search and downoad Valheim mods directly from within the manager, or update them, and you can modify config files easily within it too.  I feel like enabling disabling/enabling individual mods or starting the game in Vanilla for troubleshooting conflicts is a lot easier than Vortex too. Just a lot better experience than Vortex, even if Vortex supported Valheim.

**Comment by JohnDowson** [comment]
This mod has been [uploaded to thunderstore](https://valheim.thunderstore.io/package/JohnDowson/CropReplant/)
