### ISSUE TITLE
Onions not supported

### ISSUE THREAD

**Issue by Taraman17** [JohnDowson/CropReplant#4]
With the latest Valheim update, Onions were added to the game.

The Mod needs to be updated to use these.

**Comment by BSteezie** [comment]
Check the mod comments (posts) on Nexus.  A user updated the pickables to work with onions & onion seeds for both 2.1.1 and 0.1.6 versions. I’m using 0.1.6, which is the much better version btw.  2.1.1 is harder to use and has multiple problems, like it replants wrong crops if fields are adjacent, etc. 0.1.6 is the way to go.

**Comment by JohnDowson** [comment]
Merged #5 resolving this issue
